#GET Acls
GET https://92.222.147.159:1443/api/v1/acls
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###

#Get Acl By Id
GET https://92.222.147.159:1443/api/v1/acls/99729d05-8ac7-4073-95b1-c76662bf6877
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###

#Get Acl Nodes By Id
GET https://92.222.147.159:1443/api/v1/acls/6f550d6f-0f03-44d0-8399-cefe0e2db5e9/nodes
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved


###

#Create Acl
POST https://92.222.147.159:1443/api/v1/acls
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "server_uuid": "996e70fb-edd1-4fd3-a92d-dde0d559dcca",
    "name": "providers",
    "default": "allow",
    "description": ""
}

###
#Create Acl Node
POST https://92.222.147.159:1443/api/v1/acls/99cac1b4-8120-4efa-a9bc-0941441a3fad/nodes
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "type": "allow",
    "cidr": "5.39.35.233/32"
}

###

#Update Acl
PUT https://92.222.147.159:1443/api/v1/acls/98d96167-596d-4bcc-8f57-5e0aabf379da
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
  "name": "providers",
  "nodes": []
}

###

#Update Acl node
PUT https://92.222.147.159:1443/api/v1/acls/97c45670-5b6d-4389-9ce4-f4af45710e36/nodes/97b288fe-ebac-4de4-b2cd-f9b00bb8fe0b
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "type": "allow",
    "cidr": "1.1.1.3/32",
    "description": "ip2"
}

###

#Delete Acl
DELETE https://92.222.147.159:1443/api/v1/acls/99c8c711-dbd1-4868-8e6a-0cbb10d35d4c
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###

#Delete Acl Node
DELETE https://92.222.147.159:1443/api/v1/acls/98d96167-596d-4bcc-8f57-5e0aabf379da/nodes/996ef895-d67e-43d7-bfb6-3f5511b0872b
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved


