#GET ALL AGENTS
GET https://92.222.147.159:1443/api/v1/agents
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#GET AGENT BY ID
GET https://92.222.147.159:1443/api/v1/agents/c7b2b479-0ab5-4b6a-9eb4-8668f815b363
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#CREATE AGENT
POST https://92.222.147.159:1443/api/v1/agents
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
  "name": "oxilog demo",
  "domain_uuid": "98e7cc69-7dfe-494c-85bb-2282609083a6",
  "subscriber_uuid": "98e7ea1d-80a1-4535-960e-6090a1cc30ff",
  "options": {
    "call_timeout": 30,
    "max_no_answer": 0,
    "wrap_up_time": 2,
    "reject_delay_time": 2,
    "busy_delay_time": 2,
    "no_answer_delay_time": 20
  },
  "status": "logged-out"
}

###
#CREATE AGENT
POST https://92.222.147.159:1443/api/v1/agents
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "name": "Anis",
	"domain_uuid": "98d96541-19e5-4e50-8406-76ba8ee8bbf4",
    "subscriber_uuid": "97b427f6-0f31-485d-b85e-91f15ee0b088",
    "status": "available",
    "options": {
        "call_timeout": 60,
        "max_no_answer": 0,
        "wrap_up_time": 10,
        "reject_delay_time": 90,
        "busy_delay_time": 90,
        "no_answer_delay_time": 20
    },
    "queues": [
        {
            "queue_uuid": "ecb6d249-436e-44c4-82bd-36cde3f5b0a4",
            "tier_level": 1,
            "tier_position": 1
        }
    ]
}

###
#UPDATE AGENT
PUT https://92.222.147.159:1443/api/v1/agents/3f885201-8b7c-44a7-a0fc-bcd33b378d49
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
  "domain_uuid": "996d6199-62c3-41e4-8c9d-4aa497ea4fe5",
  "subscriber_uuid": "996d62f7-381d-4a18-83ea-6fe01ce20ca2",
  "name": "1013",
    "enabled": true,
    "options": {
        "call_timeout": 60,
        "max_no_answer": 0,
        "wrap_up_time": 10,
        "reject_delay_time": 90,
        "busy_delay_time": 90,
        "no_answer_delay_time": 20
    }
}

###
#GET AGENT SIPINFO BY ID
GET https://92.222.147.159:1443/api/v1/agents/20b61f6e-0994-4ce3-a851-b79e3d5d61eb/sipinfo
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#GET AGENT TIERS BY ID
GET https://92.222.147.159:1443/api/v1/agents/28379d77-96a5-4b81-969e-1109fe7e7893/tiers
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#UPDATE AGENT level & position on a queue
PUT https://92.222.147.159:1443/api/v1/agents/b3463bca-01f9-4830-8094-5f4e1c486a3b/tier
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "queue_uuid": "0e4c3448-dff9-4381-a38d-800635f16c45",
    "tier_level": 1,
    "tier_position": 1
}

###
#UPDATE AGENT STATUS
PUT https://92.222.147.159:1443/api/v1/agents/18e5d8c4-8cbb-4ae3-bfab-a5f1a306b701/status
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "status": "logged-out"
}

###
#DELETE AGENT
DELETE https://92.222.147.159:1443/api/v1/agents/1
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

