###
# GET ALL GATEWAYS

GET https://92.222.147.159:1443/api/v1/gateways
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
# GET GATEWAY BY UUID

GET https://92.222.147.159:1443/api/v1/gateways/1
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
# CREATE NEW GATEWAY

POST https://92.222.147.159:1443/api/v1/gateways
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
	"name":"oxilog",
	"server_uuid": "98d9429a-1939-47f5-9c1e-39643a623a90",
	"username":"oxilog",
	"proxy":"sip.oxilog.net",
	"register":false,
	"caller_id_in_from":true,
	"extension":"oxilog",
	"extension_in_contact":true,
	"codec_prefs":"PCMA"
}


###
# CREATE NEW GATEWAY

POST https://92.222.147.159:1443/api/v1/gateways
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
	"name":"test",
	"server_uuid": "98d9429a-1939-47f5-9c1e-39643a623a90",
	"username":"102",
	"password":"Bn7a2nz2LR$hjHkE.Z%o",
	"proxy":"ipbx1.voxnode.com",
	"register":true,
	"expire_seconds":900,
	"retry_seconds":90,
	"caller_id_in_from":true,
	"extension":"test",
	"extension_in_contact":true,
	"codec_prefs":"PCMA,PCMU"
}

###
# UPDATE GATEWAY BY UUID

PUT https://92.222.147.159:1443/api/v1/gateways/98e7f98f-908e-4e8c-8b4f-235665073c77
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
  "uuid": "98dfa824-1a4e-4ae6-a955-0df701432041",
  "server_uuid": "98d9429a-1939-47f5-9c1e-39643a623a90",
  "name": "truncktest",
  "username": "",
  "password": "",
  "realm": "",
  "proxy": "51.89.255.43",
  "outbound_proxy": "",
  "register": false,
  "register_proxy": "",
  "register_transport": "udp",
  "expire_seconds": 900,
  "retry_seconds": 90,
  "distinct_to": false,
  "auth_username": "",
  "from_user": "",
  "from_domain": "",
  "caller_id_in_from": true,
  "extension": "",
  "extension_in_contact": false,
  "contact_params": "",
  "ping": 0,
  "supress_cng": false,
  "sip_cid_type": "none",
  "codec_prefs": "PCMA",
  "channels": 1000,
  "enabled": true,
  "created_at": "2023-04-07T10:34:20.000000Z",
  "updated_at": "2023-04-07T10:34:20.000000Z"
}


###

# DELETE GATEWAY BY UUID
DELETE https://92.222.147.159:1443/api/v1/gateways/98d9633f-ba70-4916-a392-de1fc089773a
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved
