#GET ALL QUEUES
GET https://92.222.147.159:1443/api/v1/queues
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#GET QUEUE BY ID
GET https://92.222.147.159:1443/api/v1/queues/8ea75643-9815-4b3e-ae69-be1255260caf
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#CREATE NEW QUEUE

POST https://92.222.147.159:1443/api/v1/queues
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "name": "50000",
    "extension": "5000",
	"domain_uuid": "98d96541-19e5-4e50-8406-76ba8ee8bbf4",
    "strategy": "ring-all",
    "greetings": [],
    "hold_music": [],
    "record": true,
    "options": {
        "time_base_score": "queue",
        "tier_rules_apply": "false",
        "tier_rule_wait_second": 300,
        "tier_rule_wait_multiply_level": "false",
        "tier_rule_no_agent_no_wait": "true",
        "discard_abandoned_after": 900,
        "abandoned_resume_allowed": "true",
        "max_wait_time": 0,
        "max_wait_time_with_no_agent": 120,
        "max_wait_time_with_no_agent_time_reached": 5,
        "ring_progressively_delay": 10,
		"skip_agents_with_external_calls": "false",
		"agent_no_answer_status": "on-break"
    }
}


###
#UPDATE QUEUE

PUT https://92.222.147.159:1443/api/v1/queues/97868d0e-1fa8-4f42-b594-22927aef7a26
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
  "domain_uuid": "98d96541-19e5-4e50-8406-76ba8ee8bbf4",
  "extension": "401892675942",
  "name": "401892675942",
  "strategy": "longest-idle-agent",
  "record": true,
  "greetings": [],
  "hold_music": [],
  "options": {
    "time_base_score": "queue",
    "tier_rules_apply": "false",
    "tier_rule_wait_second": 300,
    "tier_rule_wait_multiply_level": "false",
    "tier_rule_no_agent_no_wait": "true",
    "discard_abandoned_after": 900,
    "abandoned_resume_allowed": "true",
    "max_wait_time": 50,
    "max_wait_time_with_no_agent": 120,
    "max_wait_time_with_no_agent_time_reached": 5,
    "ring_progressively_delay": 10,
    "skip_agents_with_external_calls": "true",
    "agent_no_answer_status": "available"
  }
}



###
#DELETE QUEUE


DELETE https://92.222.147.159:1443/api/v1/queues/97868d0e-1fa8-4f42-b594-22927aef7a26
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#GET QUEUE TIERS

GET https://92.222.147.159:1443/api/v1/queues/9d0611f5-989f-4e5b-b9d1-dcbcef3f568f/tiers
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#ADD/UPDATE QUEUE TIERS

POST https://92.222.147.159:1443/api/v1/queues/0e4c3448-dff9-4381-a38d-800635f16c45/tiers
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "tiers": [
        {
            "agent_uuid": "b3463bca-01f9-4830-8094-5f4e1c486a3b",
            "tier_level": 1,
            "tier_position": 1
        }
    ]
}

###
#DELETE QUEUE TIERS

POST https://92.222.147.159:1443/api/v1/queues/41ee100d-086f-49dc-afa1-6b74f7221653/tiers/delete
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "agents": ["28379d77-96a5-4b81-969e-1109fe7e7893", "c426c0e5-dd20-4fd1-8297-a6e078f9d505"]
}


###
#DELETE ALL QUEUE TIERS AT ONCE

POST https://92.222.147.159:1443/api/v1/queues/deaa7ce4-9078-47b7-aee3-d15bc21e3870/tiers/delete
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "agents": ["*"]
}


###
#CLEAR QUEUE CALLS
GET https://92.222.147.159:1443/api/v1/queues/8ea75643-9815-4b3e-ae69-be1255260caf/clear
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved
