#GET ALL SUBSCRIBERS
GET https://92.222.147.159:1443/api/v1/subscribers
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#GET SUBSCRIBER BY ID
GET https://92.222.147.159:1443/api/v1/subscribers/98e7ea1d-80a1-4535-960e-6090a1cc30ff
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved
###

#GET SUBSCRIBER BY USERNAME
GET https://92.222.147.159:1443/api/v1/subscribers/username/anis
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#GET SUBSCRIBER STATUS
GET https://92.222.147.159:1443/api/v1/subscribers/97b28d30-d7c3-432b-b376-53d2b13c0166/status
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
#CREATE SUBSCRIBER WITH Username/Password Auth
POST https://92.222.147.159:1443/api/v1/subscribers
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "username":"anis",
    "domain":"sip-preaconis.skycrm360.io",
    "password":"anis998877!!"
}

###
#UPDATE SUBSCRIBER
PUT https://92.222.147.159:1443/api/v1/subscribers/97b28d30-d7c3-432b-b376-53d2b13c0166
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
    "username":"anis",
    "domain":"92.222.147.159",
    "password":"pwdpwdpwd",
    "enabled": true
}

###
#DELETE SUBSCRIBER BY ID
DELETE https://92.222.147.159:1443/api/v1/subscribers/9903ae0a-16cd-45c1-a46a-a9ce33ff8ae0
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved
