###
# GET ALL GATEWAYS

GET https://sip-crm.oxilog-telecom.net:1443/api/v1/gateways
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
# GET GATEWAY BY UUID

GET https://sip-crm.oxilog-telecom.net:1443/api/v1/gateways/1
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

###
# CREATE NEW GATEWAY

POST https://sip-crm.oxilog-telecom.net:1443/api/v1/gateways
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
	"name":"oxilog",
	"domain_uuid": "97c0468b-59b9-42b8-adc8-aa9749f1f8c8",
	"username":"115093553888",
    "password": "MtN97zcl8D76XoURYInbkmLr",
	"proxy":"sip2.oxilog.net",
	"register":false,
	"caller_id_in_from":true,
	"extension":"oxilog",
	"extension_in_contact":true,
	"codec_prefs":"PCMA"
}


###
# CREATE NEW GATEWAY

POST https://sip-crm.oxilog-telecom.net:1443/api/v1/gateways
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
	"name":"test",
	"domain_uuid": "97b28779-7e15-4e24-9587-e3e1ee87e44d",
	"username":"102",
	"password":"Bn7a2nz2LR$hjHkE.Z%o",
	"proxy":"ipbx1.voxnode.com",
	"register":true,
	"expire_seconds":900,
	"retry_seconds":90,
	"caller_id_in_from":true,
	"extension":"test",
	"extension_in_contact":true,
	"codec_prefs":"PCMA,PCMU"
}

###
# UPDATE GATEWAY BY UUID

PUT https://sip-crm.oxilog-telecom.net:1443/api/v1/gateways/97b28b78-f430-4b09-98bd-f05d46ffebbd
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved

{
	"name": "VOS3000",
	"domain_uuid": "97b28779-7e15-4e24-9587-e3e1ee87e44d",
	"username": "callcenter",
	"password": "",
	"realm": "",
	"proxy": "51.222.183.77",
	"outbound_proxy": "",
	"register": false,
	"register_proxy": "",
	"register_transport": "udp",
	"expire_seconds": 900,
	"retry_seconds": 90,
	"distinct_to": false,
	"auth_username": "",
	"from_user": "",
	"from_domain": "",
	"caller_id_in_from": true,
	"extension": "callcenter",
	"extension_in_contact": true,
	"contact_params": "",
	"ping": 0,
	"supress_cng": false,
	"sip_cid_type": "pid",
	"codec_prefs": "PCMA",
	"channels": 0,
	"enabled": true
}


###

# DELETE GATEWAY BY UUID
DELETE https://sip-crm.oxilog-telecom.net:1443/api/v1/gateways/97b28b78-f430-4b09-98bd-f05d46ffebbd
Content-Type: application/json
Authorization: Bearer BomjNx8kFfZTdCFx4kH3hGECO78yS0C0KS7pgO0BUe8COxcved
